### ISSUE TITLE
First Task

### ISSUE THREAD

**Issue by VVotan** [JohannesWesch/SpeechTranslation#1]
### Todo
- [x] Split up dataset into dev, test, train
- [x] use new datasets in the notebook
- [x] train the model with hyperparameters/colab 
- [x] use different evaluation methods to evaluate the model
- [x] write a lab report about the findings
- [x] find out how to run a jupyter notebook on the bwUniCluster 2.0 
  - See #2
